version: '3.8'

services:
  k6:
    image: grafana/k6
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    command: run test1.js
    depends_on:
      - api
  
  api:
    build: .
    ports:
      - "3000:3000"
    container_name: mi-api