name: Run k6 Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  k6-smoke-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run k6 smoke test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: ./scripts/TestSmoke.js
